name: Deploy MerchantDemo til TEST

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy MerchantDemo til TEST
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4



      - name: Deploy til TEST Static Web App
        run: |
          npx @azure/static-web-apps-cli deploy src/Frontend.MerchantDemo \
            --deployment-token ${{ secrets.SWA_TOKEN_MERCHANT_TEST }} \
            --env production
          echo "MerchantDemo deployed til: https://brave-flower-0026a7503.7.azurestaticapps.net"
